### ISSUE TITLE
Add lib for iPhone rather than just iPhone Sim?

### ISSUE THREAD

**Issue by Workings** [NamCkiku/GoogleMapsUtils#1]
Having problems compiling with iphone as only have simulator lib in there?

**Comment by damiand2** [comment]
as above, error: 
ld: in /Users/runner/work/1/s/xxx/obj/Release/net7.0-ios/ios-arm64/linker-cache/GoogleMapsUtils.framework/GoogleMapsUtils(GoogleMapsUtils_vers.o), building for iOS, but linking in object file built for iOS Simulator, file '/Users/runner/work/1/s/xxx/obj/Release/net7.0-ios/ios-arm64/linker-cache/GoogleMapsUtils.framework/GoogleMapsUtils'

**Comment by damiand2** [comment]
@Workings - i created nuget that works with real phones also - 	GMapUtils.iOS, you can also use GMapUtils.Android with latest native libraries
